name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Hər gün UTC vaxtı ilə saat 00:00-da avtomatik işləyəcək
  workflow_dispatch: # Əl ilə işə salmaq üçün
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: YOUR_USERNAME # Burada istifadəçi adınızı qeyd edin
          outputs: dist/snake.svg

      - name: Push the changes
        uses: github-actions-x/commit@v3
        with:
          commit_message: "Generated snake animation"
          files: dist/snake.svg
