name: Generate Snake

on:
  schedule:
    # Hər 6 saatdan bir işləsin
    - cron: "0 */6 * * *"
  workflow_dispatch: # Əl ilə də işə salmaq mümkündür

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v2
        with:
          github_user_name: Emil1ff # Burada istifadəçi adınızı qeyd edin
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push the changes
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
